export const weather_mapping = {
  Sunny: "CLEAR_DAY",
  Clear: "CLEAR_NIGHT",
  "Partly cloudy": "PARTLY_CLOUDY_DAY",
  "Partly cloudy day": "PARTLY_CLOUDY_DAY",
  "Partly cloudy night": "PARTLY_CLOUDY_NIGHT",
  Cloudy: "CLOUDY",
  Mist: "FOG",
  "Patchy rain possible": "RAIN",
  "Patchy snow possible": "SNOW",
  "Patchy sleet possible": "SLEET",
  "Patchy freezing drizzle possible": "SLEET",
  "Thundery outbreaks possible": "RAIN",
  "Blowing snow": "SNOW",
  Blizzard: "SNOW",
  Fog: "FOG",
  "Freezing fog": "FOG",
  "Patchy light drizzle": "RAIN",
  "Light drizzle": "RAIN",
  "Freezing drizzle": "SLEET",
  "Heavy freezing drizzle": "SLEET",
  "Patchy light rain": "RAIN",
  "Light rain": "RAIN",
  "Moderate rain at times": "RAIN",
  "Moderate rain": "RAIN",
  "Heavy rain at times": "RAIN",
  "Heavy rain": "RAIN",
  "Light freezing rain": "SLEET",
  "Moderate or heavy freezing rain": "SLEET",
  "Light sleet": "SLEET",
  "Moderate or heavy sleet": "SLEET",
  "Patchy light snow": "SNOW",
  "Light snow": "SNOW",
  "Patchy moderate snow": "SNOW",
  "Moderate snow": "SNOW",
  "Patchy heavy snow": "SNOW",
  "Heavy snow": "SNOW",
  "Ice pellets": "SLEET",
  "Light rain shower": "RAIN",
  "Moderate or heavy rain shower": "RAIN",
  "Torrential rain shower": "RAIN",
  "Light sleet showers": "SLEET",
  "Moderate or heavy sleet showers": "SLEET",
  "Light snow showers": "SNOW",
  "Moderate or heavy snow showers": "SNOW",
  "Light showers of ice pellets": "SLEET",
  "Moderate or heavy showers of ice pellets": "SLEET",
  "Patchy light rain with thunder": "RAIN",
  "Moderate or heavy rain with thunder": "RAIN",
  "Patchy light snow with thunder": "SNOW",
  "Moderate or heavy snow with thunder": "SNOW",
};
